// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CustemListitem: typeof import('./src/components/custem-listitem.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCalendar: typeof import('@nutui/nutui-taro')['Calendar']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCellGroup: typeof import('@nutui/nutui-taro')['CellGroup']
    NutEmpty: typeof import('@nutui/nutui-taro')['Empty']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutRate: typeof import('@nutui/nutui-taro')['Rate']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutSignature: typeof import('@nutui/nutui-taro')['Signature']
    NutSticky: typeof import('@nutui/nutui-taro')['Sticky']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    NutTextarea: typeof import('@nutui/nutui-taro')['Textarea']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
  }
}
